development:
  primary:
    adapter: postgresql
    database: blog_development
    username: postgres
    password: <%= ENV['PASSWORD'] %>
  primary_replica:
    adapter: postgresql
    database: blog_development
    username: postgres_readonly
    password: <%= ENV['READONLY_PASSWORD'] %>
    replica: true
  album:
    adapter: postgresql
    database: album_development
    username: postgres
    password: <%= ENV['ALBUM__PASSWORD'] %>
    migrations_paths: db/album_migrate
  album_replica:
    adapter: postgresql
    database: album_development
    username: postgres_readonly
    password: <%= ENV['ALBUM_READONLY_PASSWORD'] %>
    replica: true

test:
  primary:
    adapter: postgresql
    database: blog_test
    username: postgres
    password: <%= ENV['TEST_PASSWORD'] %>
  primary_replica:
    adapter: postgresql
    database: blog_test
    username: postgres_readonly
    password: <%= ENV['TEST_READONLY_PASSWORD'] %>
    replica: true
  album:
    adapter: postgresql
    database: album_test
    username: postgres
    password: <%= ENV['TEST_ALBUM__PASSWORD'] %>
    migrations_paths: db/album_migrate
  album_replica:
    adapter: postgresql
    database: album_test
    username: postgres_readonly
    password: <%= ENV['TEST_ALBUM_READONLY_PASSWORD'] %>
    replica: true
